title: <p align="center"> Binay Prasad Yadab </p>
logo: <center><img src="/assets/img/Passport Size photo-min.jpg"/></center>

description:
  <p align="center">
  <a href="https://github.com/Byadab">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also working on data governece, data protection.
  Working in FinTech domain for 1 years.
  <br>
  </p>
theme: jekyll-theme-minimal
