title: <p align="center"> Binay Prasad Yadab </p>
logo: <img src="/assets/img/Passport Size photo-min.jpg" alt="drawing" width="200"/>

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also working on data governece, data protection.
  Working in FinTech domain for 1 years.
  <br>
  </p>
theme: jekyll-theme-minimal
